// generated by Textmapper; DO NOT EDIT

package ast

// Interfaces.

type TypelessNode interface {
	TypelessNode() *Node
}

type NilNode struct {}

var nilInstance = &NilNode{}

// All types implement TypelessNode.
func (NilNode) TypelessNode() *Node { return nil }

// Types.


