// generated by Textmapper; DO NOT EDIT

package ast

import (
	"fmt"
	"github.com/llir/ll"
)

func ToTypelessNode(n *Node) TypelessNode {
	switch n.Type() {
	case ll.NoType:
	  return nilInstance
	}
	panic(fmt.Errorf("ast: unknown node type %v", n.Type()))
	return nil
}
