// generated by Textmapper; DO NOT EDIT

package typeless

import (
	"fmt"
)

// Token is an enum of all terminal symbols of the typeless language.
type Token int

// Token values.
const (
	UNAVAILABLE Token = iota-1
	EOI

	INVALID_TOKEN
	IDENTIFIER_TOK
	LPAREN // (
	RPAREN // )
	LBRACK // [
	RBRACK // ]
	COMMA // ,
	ESC // \\
	MINUSGT // ->
	INTLIT

	NumTokens
)

var tokenStr = [...]string{
	"EOI",

	"INVALID_TOKEN",
	"IDENTIFIER_TOK",
	"(",
	")",
	"[",
	"]",
	",",
	"\\\\",
	"->",
	"INTLIT",
}

func (tok Token) String() string {
	if tok >= 0 && int(tok) < len(tokenStr) {
		return tokenStr[tok]
	}
	return fmt.Sprintf("token(%d)", tok)
}
